### ISSUE TITLE
I am working on a awesome-python-htmx, seeking your feedback

### ISSUE THREAD

**Issue by benjamin-kirkbride** [guettli/html_form_to_dict#2]
A few of us at PyCon this year got together and brainstormed a new Web Stack that we are calling PyHAT (Python, htmx, ASGI, TailwindCSS). The first thing we set out to do is create [awesome-python-htmx](https://github.com/PyHAT-stack/awesome-python-htmx/blob/main/README.md); a collection of active tools/libraries/projects in that space.

Your project seems like an obvious thing to include, so I did so under "tools". I'd appreciate your feedback if you have any on it's inclusion.

In addition to that, if you could also participate in https://github.com/PyHAT-stack/awesome-python-htmx/discussions/1 that would be greatly appreciated!

**Comment by guettli** [comment]
Sorry, I can't help at the moment. I am doing Kubernetes and Go at the moment. But talk to the people at the htmx discord, or people on reddit, and I guess you will get feedback.

My feedback: In Go the advice is to use the standard library for web development. This changed my mind a bit. So why do you want to wire things together, which are standalone tools? Maybe you could provide docs and an example project about how to use these tools together. Maybe no framework is required, and docs are enough?

**Comment by benjamin-kirkbride** [comment]
Thanks for your response, and your advice. I will take it into consideration.
